// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp_Bt0x0c4UFBMLWJAT8wfjQ6MuVZDMME',
    appId: '1:709957401040:web:2140e88891d5dc461621d5',
    messagingSenderId: '709957401040',
    projectId: 'mybete-app',
    authDomain: 'mybete-app.firebaseapp.com',
    storageBucket: 'mybete-app.firebasestorage.app',
    measurementId: 'G-E33W0Z9BMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ysPd8SbKJ4GrJn2IJpiVZiKizjIVuG8',
    appId: '1:709957401040:android:42e60b2f602e97071621d5',
    messagingSenderId: '709957401040',
    projectId: 'mybete-app',
    storageBucket: 'mybete-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU54bLr-ZSNuC4niwEtCmcTkIIEMxTKpw',
    appId: '1:709957401040:ios:e5ee60d183507b001621d5',
    messagingSenderId: '709957401040',
    projectId: 'mybete-app',
    storageBucket: 'mybete-app.firebasestorage.app',
    iosBundleId: 'com.example.mybeteApp',
  );
}
